// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMlo6JRFMy57ttvDCw-4ZL3TnKQb4bw1c',
    appId: '1:31407770985:web:e0463b71d44cca68f1c1f8',
    messagingSenderId: '31407770985',
    projectId: 'test-9464f',
    authDomain: 'test-9464f.firebaseapp.com',
    storageBucket: 'test-9464f.firebasestorage.app',
    measurementId: 'G-VS5LJQ370F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoirfZoEItckZAG0SGp6UfBTi_HxFia6w',
    appId: '1:31407770985:android:4cc9bb41ce829aa2f1c1f8',
    messagingSenderId: '31407770985',
    projectId: 'test-9464f',
    storageBucket: 'test-9464f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN7_7VlnO0wraknN8nDWsia-VdaH74t00',
    appId: '1:31407770985:ios:5f73995c2ff41204f1c1f8',
    messagingSenderId: '31407770985',
    projectId: 'test-9464f',
    storageBucket: 'test-9464f.firebasestorage.app',
    iosBundleId: 'com.example.flutterGemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN7_7VlnO0wraknN8nDWsia-VdaH74t00',
    appId: '1:31407770985:ios:5f73995c2ff41204f1c1f8',
    messagingSenderId: '31407770985',
    projectId: 'test-9464f',
    storageBucket: 'test-9464f.firebasestorage.app',
    iosBundleId: 'com.example.flutterGemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMlo6JRFMy57ttvDCw-4ZL3TnKQb4bw1c',
    appId: '1:31407770985:web:10b93e5c38cf718af1c1f8',
    messagingSenderId: '31407770985',
    projectId: 'test-9464f',
    authDomain: 'test-9464f.firebaseapp.com',
    storageBucket: 'test-9464f.firebasestorage.app',
    measurementId: 'G-X2DJQQMK7C',
  );

}